-- Crear BD de ejemplo

CREATE DATABASE BD64751;
GO

USE BD64751;
GO

SELECT * FROM CLIENTE;
GO

INSERT INTO CLIENTE(NOMBRE) VALUES('GUSTAVO CORONEL');
INSERT INTO CLIENTE(NOMBRE) VALUES('KIMBERLY GONZALEZ');
INSERT INTO CLIENTE(NOMBRE) VALUES('KAREN GREIG');
INSERT INTO CLIENTE(NOMBRE) VALUES('ALESSANDRA GARCIA GODOS');
INSERT INTO CLIENTE(NOMBRE) VALUES('ALVARO SAENZ');
INSERT INTO CLIENTE(NOMBRE) VALUES('CESAR ALBARRACIN');
INSERT INTO CLIENTE(NOMBRE) VALUES('AARON SALVADOR');
INSERT INTO CLIENTE(NOMBRE) VALUES('PEDRO CASTILLO');
INSERT INTO CLIENTE(NOMBRE) VALUES('ROCIO LEON');
INSERT INTO CLIENTE(NOMBRE) VALUES('CRISTHIAN VARGAS');
INSERT INTO CLIENTE(NOMBRE) VALUES('VERONICA INFANTE');
INSERT INTO CLIENTE(NOMBRE) VALUES('CHRISTIAN ROBLEDO');
GO

SELECT * FROM PRODUCTO;
GO

INSERT INTO PRODUCTO(NOMBRE,STOCK,PRECIO) VALUES('LAPTOP',100,4890.0);
INSERT INTO PRODUCTO(NOMBRE,STOCK,PRECIO) VALUES('CELULAR',200,1490.0);
INSERT INTO PRODUCTO(NOMBRE,STOCK,PRECIO) VALUES('AGENDA',50,69.0);
INSERT INTO PRODUCTO(NOMBRE,STOCK,PRECIO) VALUES('IMPRESORA',80,750.0);
INSERT INTO PRODUCTO(NOMBRE,STOCK,PRECIO) VALUES('IPHONE',500,7000.0);
INSERT INTO PRODUCTO(NOMBRE,STOCK,PRECIO) VALUES('LICUADORA',24,30.0);
INSERT INTO PRODUCTO(NOMBRE,STOCK,PRECIO) VALUES('TV',50,2000.0);
GO


SELECT * FROM VENTA;
GO

INSERT INTO VENTA(IDCLIENTE,FECHA,TOTAL) VALUES(3,'20240102',0);
INSERT INTO VENTA(IDCLIENTE,FECHA,TOTAL) VALUES(1,'20240112',0);
INSERT INTO VENTA(IDCLIENTE,FECHA,TOTAL) VALUES(8,'20240802',9);
INSERT INTO VENTA(IDCLIENTE,FECHA,TOTAL) VALUES(8,'20240122',2);
INSERT INTO VENTA(IDCLIENTE,FECHA,TOTAL) VALUES(3,'20240302',20);
INSERT INTO VENTA(IDCLIENTE,FECHA,TOTAL) VALUES(6,'20240101',800);
INSERT INTO VENTA(IDCLIENTE,FECHA,TOTAL) VALUES(4,'20240503',600);
GO

SELECT * FROM DETALLE;
GO

-- VENTA 1

INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(1,2,3,0,0);
INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(1,4,2,0,0);
INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(1,7,4,0,0);
GO

-- VENTA 2

INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(2,3,4,0,0);INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(2,7,3,0,0);INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(2,1,2,0,0);
GO


-- VENTA 3

INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(3,2,10,0,0);INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(3,4,18,0,0);INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(3,5,12,0,0);


-- VENTA 4

INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(4,2,3,0,0);INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(4,3,1,0,0);INSERT INTO DETALLE(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIO,SUBTOTAL) VALUES(4,7,5,0,0);-- VENTA 5-- VENTA 6-- VENTA 7-- ACTUALIZAR EL PRECIO DE VENTA
SELECT * FROM DETALLE;
GO

UPDATE DETALLE 
SET PRECIO = P.PRECIO
FROM DETALLE D JOIN PRODUCTO P
ON D.IDPRODUCTO = P.IDPRODUCTO;
GO

-- ACTUALIZAR EL SUBTOTAL

UPDATE DETALLE 
SET SUBTOTAL = PRECIO * CANTIDAD;
GO

SELECT * FROM DETALLE;
GO


-- ACTUALIZAR EL TOTAL

DECLARE @IDVENTA INT;
SET @IDVENTA = 7;
SELECT * FROM VENTA WHERE IDVENTA = @IDVENTA;
SELECT * FROM DETALLE WHERE IDVENTA = @IDVENTA;
GO


UPDATE VENTA 
SET TOTAL = ISNULL( (SELECT SUM(D.SUBTOTAL) FROM DETALLE D WHERE D.IDVENTA = V.IDVENTA), 0 )
FROM VENTA V;
GO






